// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/Boyuan-IT-Club/Meowpick-Backend/application/service"
	"github.com/Boyuan-IT-Club/Meowpick-Backend/infra/config"
	"github.com/Boyuan-IT-Club/Meowpick-Backend/infra/mapper/comment"
	"github.com/Boyuan-IT-Club/Meowpick-Backend/infra/mapper/searchhistory"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoMapper := comment.NewMongoMapper(configConfig)
	commentService := service.CommentService{
		CommentMapper: mongoMapper,
	}
	searchhistoryMongoMapper := searchhistory.NewMongoMapper(configConfig)
	searchHistoryService := service.SearchHistoryService{
		SearchHistoryMapper: searchhistoryMongoMapper,
	}
	providerProvider := &Provider{
		Config:               configConfig,
		CommentService:       commentService,
		SearchHistoryService: searchHistoryService,
	}
	return providerProvider, nil
}
