// Copyright 2026 Boyuan-IT-Club
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/sign_in": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "SignInReq",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SignInResp"
                        }
                    }
                }
            }
        },
        "/api/comment/add": {
            "post": {
                "description": "用户对指定课程发布评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "发布课程评论",
                "parameters": [
                    {
                        "description": "CreateCommentReq",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCommentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCommentResp"
                        }
                    }
                }
            }
        },
        "/api/comment/history": {
            "post": {
                "description": "分页获取当前用户发布过的评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "获取我的评论历史",
                "parameters": [
                    {
                        "description": "GetMyCommentsReq",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetMyCommentsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetMyCommentsResp"
                        }
                    }
                }
            }
        },
        "/api/comment/query": {
            "get": {
                "description": "根据课程ID分页查询评论列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "分页获取课程评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "courseId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListCourseCommentsResp"
                        }
                    }
                }
            }
        },
        "/api/course/campuses": {
            "get": {
                "description": "根据课程名字获取课程开课校区",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "获取课程开课校区",
                "parameters": [
                    {
                        "type": "string",
                        "description": "课程名称关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetCourseCampusesResp"
                        }
                    }
                }
            }
        },
        "/api/course/categories": {
            "get": {
                "description": "根据课程名字获取课程分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "获取课程分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "课程名称关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetCourseCategoriesResp"
                        }
                    }
                }
            }
        },
        "/api/course/departs": {
            "get": {
                "description": "根据课程名字获取课程开课院系",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "获取课程开课院系",
                "parameters": [
                    {
                        "type": "string",
                        "description": "课程名称关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetCourseDepartmentsResp"
                        }
                    }
                }
            }
        },
        "/api/course/{courseId}": {
            "get": {
                "description": "获取课程信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course"
                ],
                "summary": "获取课程信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "课程ID",
                        "name": "courseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetCourseResp"
                        }
                    }
                }
            }
        },
        "/api/like/{likeId}": {
            "post": {
                "description": "对指定目标（提案或评论）进行点赞或取消点赞操作；若已点赞则取消，未点赞则新增",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "like"
                ],
                "summary": "点赞 / 取消点赞",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标ID（提案ID或评论ID）",
                        "name": "likeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "点赞请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ToggleLikeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "$ref": "#/definitions/dto.ToggleLikeResp"
                        }
                    }
                }
            }
        },
        "/api/proposal/add": {
            "post": {
                "description": "创建一个新的提案",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "proposal"
                ],
                "summary": "新增提案",
                "parameters": [
                    {
                        "description": "创建提案的请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateProposalReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateProposalResp"
                        }
                    }
                }
            }
        },
        "/api/proposal/list": {
            "get": {
                "description": "分页查询提案列表数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proposal"
                ],
                "summary": "分页获取提案列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListProposalResp"
                        }
                    }
                }
            }
        },
        "/api/proposal/suggest": {
            "post": {
                "description": "根据关键词模糊分页搜索提案标题，返回匹配的提案建议列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proposal"
                ],
                "summary": "获取提案搜索建议",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetProposalSuggestionsResp"
                        }
                    }
                }
            }
        },
        "/api/proposal/{proposalId}": {
            "get": {
                "description": "根据提案ID查询提案完整信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proposal"
                ],
                "summary": "获取提案详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提案ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetProposalResp"
                        }
                    }
                }
            }
        },
        "/api/proposal/{proposalId}/approve": {
            "post": {
                "responses": {}
            }
        },
        "/api/proposal/{proposalId}/delete": {
            "post": {
                "description": "根据提案ID软删除提案（标记为已删除状态）",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "proposal"
                ],
                "summary": "删除提案",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提案ID",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteProposalResp"
                        }
                    }
                }
            }
        },
        "/api/proposal/{proposalId}/update": {
            "post": {
                "description": "根据提案ID修改提案的标题和内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proposal"
                ],
                "summary": "更新提案内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "提案唯一ID",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新参数（标题、内容）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProposalReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功响应",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProposalResp"
                        }
                    }
                }
            }
        },
        "/api/search": {
            "post": {
                "description": "搜索课程列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "搜索课程列表",
                "parameters": [
                    {
                        "description": "ListCoursesReq",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ListCoursesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListCoursesResp"
                        }
                    }
                }
            }
        },
        "/api/search/recent": {
            "get": {
                "description": "获取最近搜索历史",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "获取最近搜索历史",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetSearchHistoriesResp"
                        }
                    }
                }
            }
        },
        "/api/search/suggest": {
            "get": {
                "description": "根据关键词获取搜索建议\n根据 type 不同执行不同的搜索逻辑：\n- course：模糊分页搜索课程\n- teacher：精确分页搜索教师开设的课程\n- category：精确分页搜索该类别下的课程\n- department：精确分页搜索该开课院系下的课程",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "获取搜索建议",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetSearchSuggestionsResp"
                        }
                    }
                }
            }
        },
        "/api/search/total": {
            "get": {
                "description": "获取系统中所有课程评论的总数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "获取吐槽总数",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetTotalCourseCommentsCountResp"
                        }
                    }
                }
            }
        },
        "/api/teacher/add": {
            "post": {
                "description": "新建教师",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teacher"
                ],
                "summary": "新建教师",
                "parameters": [
                    {
                        "description": "CreateTeacherReq",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTeacherReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTeacherResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CommentVO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "courseId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "like": {
                    "type": "boolean"
                },
                "likeCnt": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teachers": {
                    "description": "这里还是直接返回教师名字+职称组合后的字符串列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.CourseVO": {
            "type": "object",
            "properties": {
                "campuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tagCount": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "teachers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TeacherVO"
                    }
                }
            }
        },
        "dto.CreateCommentReq": {
            "type": "object",
            "required": [
                "content",
                "courseId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "courseId": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.CreateCommentResp": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "courseId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "like": {
                    "type": "boolean"
                },
                "likeCnt": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teachers": {
                    "description": "这里还是直接返回教师名字+职称组合后的字符串列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.CreateProposalReq": {
            "type": "object",
            "required": [
                "content",
                "course",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "course": {
                    "$ref": "#/definitions/dto.CourseVO"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.CreateProposalResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "proposalId": {
                    "description": "提案ID",
                    "type": "string"
                }
            }
        },
        "dto.CreateTeacherReq": {
            "type": "object",
            "required": [
                "department",
                "name",
                "title"
            ],
            "properties": {
                "department": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.CreateTeacherResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteProposalResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "deleted": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "operatorId": {
                    "type": "string"
                },
                "proposalId": {
                    "type": "string"
                }
            }
        },
        "dto.GetCourseCampusesResp": {
            "type": "object",
            "properties": {
                "campuses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.GetCourseCategoriesResp": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.GetCourseDepartmentsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "departments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.GetCourseResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "course": {
                    "$ref": "#/definitions/dto.CourseVO"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.GetMyCommentsReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                }
            }
        },
        "dto.GetMyCommentsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CommentVO"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.GetProposalResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "proposal": {
                    "$ref": "#/definitions/dto.ProposalVO"
                }
            }
        },
        "dto.GetProposalSuggestionsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "suggestions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProposalSuggestionsVO"
                    }
                }
            }
        },
        "dto.GetSearchHistoriesResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SearchHistoryVO"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.GetSearchSuggestionsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "suggestions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SearchSuggestionsVO"
                    }
                }
            }
        },
        "dto.GetTotalCourseCommentsCountResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.ListCourseCommentsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CommentVO"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ListCoursesReq": {
            "type": "object",
            "properties": {
                "keyword": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "type": {
                    "description": "teacher or course",
                    "type": "string"
                }
            }
        },
        "dto.ListCoursesResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "courses": {
                    "description": "当前页的课程列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CourseVO"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "description": "符合条件的总记录数",
                    "type": "integer"
                }
            }
        },
        "dto.ListProposalResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "proposals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProposalVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.ProposalSuggestionsVO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ProposalVO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "course": {
                    "$ref": "#/definitions/dto.CourseVO"
                },
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "like": {
                    "type": "boolean"
                },
                "likeCnt": {
                    "type": "integer"
                },
                "status": {
                    "description": "pending / approved / rejected",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.SearchHistoryVO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "dto.SearchSuggestionsVO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.SignInReq": {
            "type": "object",
            "required": [
                "authId",
                "authType",
                "verifyCode"
            ],
            "properties": {
                "authId": {
                    "description": "微信开放平台ID",
                    "type": "string"
                },
                "authType": {
                    "description": "认证类型(wechat/phone等)",
                    "type": "string"
                },
                "verifyCode": {
                    "description": "res.code",
                    "type": "string"
                }
            }
        },
        "dto.SignInResp": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "expiresIn": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.TeacherVO": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ToggleLikeReq": {
            "type": "object",
            "properties": {
                "targetId": {
                    "type": "string"
                },
                "targetType": {
                    "description": "1: \"proposal\"，2: \"comment\"",
                    "type": "string"
                }
            }
        },
        "dto.ToggleLikeResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "like": {
                    "type": "boolean"
                },
                "likeCnt": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProposalReq": {
            "type": "object",
            "required": [
                "content",
                "course",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "course": {
                    "$ref": "#/definitions/dto.CourseVO"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProposalResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "proposalId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Meowpick Backend API",
	Description:      "选课猫后端接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
